# Project Information
site_name: SINCLAIR
site_author: CCR Collaborative Bioinformatics Resource
site_description: >-
  SINCLAIR is an open-source, reproducible solution for multiple single cell next-generation modalities
# Repository
repo_name: CCBR/SINCLAIR
repo_url: https://github.com/CCBR/SINCLAIR
edit_uri: https://github.com/CCBR/SINCLAIR/edit/feature/gex_only/docs/

# Copyright
copyright: Copyright &copy; 2023-{{ now().year }} CCR Collaborative Bioinformatics Resource

# Configuration
theme:
  name: readthedocs
  locale: en
  custom_dir: docs/overrides

# Plugins
plugins:
  - search
  - git-revision-date
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/solid/users
      link: http://bioinformatics.cancer.gov
    - icon: fontawesome/brands/github
      link: https://github.com/CCBR
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/orgs/nciccbr/repositories

extra_css:
  - css/custom.css
extra_javascript:
  - js/custom.js

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.md_in_html
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page Tree
nav:
  - Background: index.md
  - Quickstart: user-guide/quickstart.md
  - Usage:
      - 1. Getting Started: user-guide/getting-started.md
      - 2. Preparing Files: user-guide/preparing-files.md
      - 3. Running the Pipeline: user-guide/run.md
      - 4. Expected Output: user-guide/output.md
      - 5. Running Test Data: user-guide/test-info.md
  - Analysis:
      - 1. Differential Expression Analysis: user-guide/differentialExpression.md
  - FAQ:
      - Troubleshooting: user-guide/troubleshooting.md
      - How to contribute: contributing.md
      - Contributors: user-guide/contributions.md
