name: seurat
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconductor-annotationdbi
  - bioconductor-biocparallel
  - bioconductor-celldex
  - bioconductor-genomeinfodbdata
  - bioconductor-glmgampoi
  - bioconductor-org.hs.eg.db
  - bioconductor-org.mm.eg.db
  - bioconductor-orthology.eg.db
  - bioconductor-scrnaseq
  - bioconductor-singlecellexperiment
  - bioconductor-singler=2
  - r-base=4
  - r-cluster
  - r-cluster=2
  - r-cowplot
  - r-DT
  - r-essentials
  - r-evaluate>=1.0.3
  - r-farver
  - r-flexmix
  - r-future.apply
  - r-ggpubr
  - r-gridextra
  - r-harmony=0.1
  - r-hdf5r
  - r-liger=1
  - r-png
  - r-presto
  - r-remotes
  - r-reticulate
  - r-r.utils
  - r-scales
  - r-seurat=5.1
  - r-signac=1
  - r-tidyverse
  - r-tinytex
  - scvi-tools=1.2
